-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 01:21:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dc2_groupe1_hotelgamma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dc2_groupe1_hotelgamma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dc2_groupe1_hotelgamma` ;
USE `dc2_groupe1_hotelgamma` ;

-- -----------------------------------------------------
-- Table `dc2_groupe1_hotelgamma`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dc2_groupe1_hotelgamma`.`type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dc2_groupe1_hotelgamma`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dc2_groupe1_hotelgamma`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dc2_groupe1_hotelgamma`.`amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dc2_groupe1_hotelgamma`.`amenities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dc2_groupe1_hotelgamma`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dc2_groupe1_hotelgamma`.`room` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(255) NOT NULL,
  `beds` TINYINT NOT NULL,
  `persons` TINYINT NOT NULL,
  `size` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` TEXT NULL,
  `type_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  `amenities_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_type_idx` (`type_id` ASC),
  INDEX `fk_room_category1_idx` (`category_id` ASC),
  INDEX `fk_room_amenities1_idx` (`amenities_id` ASC),
  CONSTRAINT `fk_room_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `dc2_groupe1_hotelgamma`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `dc2_groupe1_hotelgamma`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_amenities1`
    FOREIGN KEY (`amenities_id`)
    REFERENCES `dc2_groupe1_hotelgamma`.`amenities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dc2_groupe1_hotelgamma`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dc2_groupe1_hotelgamma`.`photo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `alt` VARCHAR(255) NULL,
  `room_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photo_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_photo_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `dc2_groupe1_hotelgamma`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
